


/* Crear tablespace para el proyecto */
CREATE TABLESPACE LAB_EJEMPLO
DATAFILE 'LAB_EJEMPLO.dbf'
SIZE 300M;

/* PERMITE EJECUCION DE SCRIPTS DENTRO DEL TABLESPACE CREADO */
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/* Crear usuario */
CREATE USER EJEMPLO IDENTIFIED BY vallegrande
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

/* Asignar los permisos al usuario */
GRANT CREATE SESSION TO EJEMPLO;
GRANT CREATE TABLE TO EJEMPLO;
GRANT CREATE VIEW TO EJEMPLO;
GRANT CREATE PROCEDURE TO EJEMPLO;
GRANT CREATE TRIGGER TO EJEMPLO;
GRANT CREATE SEQUENCE TO EJEMPLO;
GRANT CREATE JOB TO EJEMPLO;

